"""Risk artifact export (Alur C) for Job Cowork."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

from core.types import CoworkJob, ScanResult


def build_artifact_payload(job: CoworkJob, scan: ScanResult | None) -> dict:
    findings = scan.findings if scan else []
    return {
        "job_id": job.job_id,
        "title": job.title,
        "target_url": job.target_url,
        "host_key": job.host_key,
        "scope": job.scope,
        "autonomy_level": job.autonomy_level.value,
        "status": job.status.value,
        "scan_id": job.scan_id,
        "defense_deltas": job.defense_deltas,
        "residuals": job.residuals,
        "antibody_loop_ok": job.antibody_loop_ok,
        "findings_count": job.findings_count,
        "mitigated_count": job.mitigated_count,
        "live_checks_run": job.live_checks_run,
        "approvals": [item.model_dump(mode="json") for item in job.approvals],
        "step_logs": [item.model_dump(mode="json") for item in job.step_logs],
        "findings_summary": [
            {
                "title": item.title,
                "severity": item.severity.value,
                "defense_delta": item.defense_delta.value if item.defense_delta else None,
                "endpoint": item.target_endpoint,
                "agent": item.agent,
            }
            for item in findings[:50]
        ],
    }


def render_markdown(job: CoworkJob, scan: ScanResult | None) -> str:
    lines = [
        f"# Job Cowork — {job.title}",
        "",
        f"- **Job ID:** `{job.job_id}`",
        f"- **Target:** {job.target_url}",
        f"- **Host:** {job.host_key or 'n/a'}",
        f"- **Scope:** {job.scope}",
        f"- **Autonomy:** {job.autonomy_level.value}",
        f"- **Status:** `{job.status.value}`",
        f"- **Scan ID:** {job.scan_id or 'n/a'}",
        "",
        "## Defense delta",
        "",
    ]
    if job.defense_deltas:
        lines.append("| Label | Count |")
        lines.append("| --- | --- |")
        for label, count in sorted(job.defense_deltas.items()):
            lines.append(f"| `{label}` | {count} |")
    else:
        lines.append("_No defense delta labels recorded._")

    lines.extend(
        [
            "",
            "## Antibody & verification",
            "",
            f"- **Antibody loop OK:** {job.antibody_loop_ok}",
            f"- **Live checks:** {job.live_checks_run}",
            f"- **Findings:** {job.findings_count}",
            f"- **Mitigated by edge:** {job.mitigated_count}",
            "",
            "## Residual risk",
            "",
        ]
    )
    if job.residuals:
        for item in job.residuals:
            lines.append(f"- `{item}`")
    else:
        lines.append("_None — closed OK per wasit rules._")

    lines.extend(["", "## Approvals (L0/L1 gate)", ""])
    if job.approvals:
        for item in job.approvals:
            lines.append(
                f"- {item.at.isoformat()} — **{item.operator}** ({item.autonomy_level.value}): "
                f"{'approved' if item.approved else 'rejected'}"
                + (f" — {item.note}" if item.note else "")
            )
    else:
        lines.append("_No approval recorded._")

    if scan and scan.findings:
        lines.extend(["", "## Sample findings", ""])
        for item in scan.findings[:15]:
            delta = item.defense_delta.value if item.defense_delta else "n/a"
            lines.append(f"- **{item.title}** ({item.severity.value}) — `{delta}` @ `{item.target_endpoint}`")

    lines.append("")
    lines.append("_Generated by NEX-RED Job Cowork (GaaS Edge Antibody)._")
    return "\n".join(lines)


def export_artifacts(job: CoworkJob, scan: ScanResult | None, out_dir: Path) -> Dict[str, str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    payload = build_artifact_payload(job, scan)
    json_path = out_dir / f"{job.job_id}.json"
    md_path = out_dir / f"{job.job_id}.md"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    md_path.write_text(render_markdown(job, scan), encoding="utf-8")
    return {"json": str(json_path), "markdown": str(md_path)}
